<?php

	/**
	 * Templatedatei für die Startseite/Konfiguration im Backend
	 * Normalerweise sollte hier nichts angepasst werden
	 */

	$wpsg_update_data = wpsg_get_update_data();
 
?>

<div class="wpsg_admin" id="wpsg-bs">

	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="#"><?php echo __('wpShopGermany', 'wpsg'); ?></a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
			 		<li role="presentation" class="<?php echo (($this->view['actionName'] == "index")?'active':''); ?>"><a href="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin"><?php echo __("Einstellungen", "wpsg"); ?></a></li>
					<li role="presentation" class="<?php echo (($this->view['actionName'] == "module")?'active':''); ?>"><a href="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin&amp;action=module"><?php echo __("Module", "wpsg"); ?></a></li>
					
					<?php if (current_user_can('wpsg_lizence') && wpsg_isSizedInt($wpsg_update_data['returnCode'])) { ?>			
					<li role="presentation" class="<?php echo (($this->view['actionName'] == "registrierung")?'active':''); ?>"><a href="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin&amp;action=registrierung"><?php echo __("Lizenzverwaltung", "wpsg"); ?></a></li>
					<?php } ?>
					
					<li role="presentation" class="<?php echo (($this->view['actionName'] == 'news')?'active':''); ?>"><a href="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin&action=news">
						<?php echo __('Aktuelles', 'wpsg'); ?>
						<?php $wpsg_news_unread = wpsg_news::countUnreadNews(); if (wpsg_isSizedInt($wpsg_news_unread)) { ?>
						<span class="badge" style="background-color:#D9534F;"><?php echo $wpsg_news_unread; ?></span>
						<?php } ?>			
					</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">				
					<li role="presentation" class="<?php echo (($this->view['actionName'] == "hilfe")?'active':''); ?>"><a href="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin&amp;action=hilfe"><?php echo __("Hilfe", "wpsg"); ?></a></li>
					<li role="presentation" class="<?php echo (($this->view['actionName'] == "ueber")?'active':''); ?>"><a href="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin&amp;action=ueber"><?php echo __("Über", "wpsg"); ?></a></li>
			 	</ul>
			</div>
		</div>		
	</nav>
				  	
	<div class="wpsg_admin_wrap">
		
		<div class="wpsg_msg_wrap"><hr class="wp-header-end wpsg-wp-header-end"/></div>
			
		<?php if (wpsg_isSizedString($this->view['subTemplate'])) { ?>
		<?php $this->render($this->view['subTemplate']); ?>
		<?php } ?>
		
	</div>
	
</div>