<div class="form-group form-group-sm form-textarea <?php echo ((wpsg_isSizedString($this->view['field_config']['help']))?'has-feedback':''); ?>">
	
	<?php if (wpsg_isSizedString($this->view['field_config']['fullLabel'])) { ?>
		
		<br />
	
		<label class="col-sm-12 control-label" style="text-align:left;" for="<?php echo $this->view['field_id']; ?>"><?php echo $this->view['field_label']; ?></label>
		
	<?php } ?>
	
    <?php if (!isset($this->view['field_config']['noLabel']) || $this->view['field_config']['noLabel'] != true) { ?>
	<label class="col-sm-6 control-label" for="<?php echo $this->view['field_id']; ?>"><?php echo $this->view['field_label']; ?></label>
	<?php } ?>

    <?php if (isset($this->view['field_config']['noLabel']) && $this->view['field_config']['noLabel'] == true) { ?>
	<div class="col-sm-12">
    <?php } else { ?>
    <div class="col-sm-6">
    <?php } ?>
	
		<div class="wpsg_field_wrap">
			
			<textarea <?php 
			
				if (wpsg_isTrue($this->view['field_config']['readonly'])) echo ' readonly="readonly" ';
				if (wpsg_isTrue($this->view['field_config']['disabled'])) echo ' disabled="disabled" ';
				if (wpsg_isSizedString($this->view['field_config']['style'])) echo 'style="'.$this->view['field_config']['style'].'" ';			
			
			?> class="form-control" id="<?php echo $this->view['field_id']; ?>" name="<?php echo $this->view['field_name']; ?>"><?php echo wpsg_hspc($this->view['field_value']); ?></textarea>
			
			<?php if (wpsg_isSizedString($this->view['field_config']['help'])) { ?>
				<a href="#" data-wpsg-tip="<?php echo $this->view['field_config']['help']; ?>" rel="?page=wpsg-Admin&subaction=loadHelp&noheader=1&field=<?php echo $this->view['field_config']['help']; ?>" class="glyphicon glyphicon glyphicon-question-sign form-control-feedback" aria-hidden="true"></a>
			<?php } ?>
		</div>
				
	</div>
	
	<div class="clearfix wpsg_clear"></div>
	
</div>