 <?php

	/**
	 * Render ein Variantenprodukt im Warenkorb (basket.phtml)
	 */
	
?>
 
<div class="product_info">
	<div class="title">
		<span class="fa  fa-share-alt"></span>
		<?php echo __("Variante", "wpsg"); ?>:
		
		
		
		<?php if (get_option('wpsg_vp_detailview') == 1) { ?>
		<?php foreach ($this->view['variante'] as $vari => $value) { ?>
		
		<?php if (is_numeric($vari)) { ?>
		<?php echo $value['name'] ?>: 
		<strong>
		<?php echo $value['value'] ?>; <?php echo __('Art. Nr.', 'wpsg').': '.$value['artnr'] ?>; 
		<?php if ($this->callMod('wpsg_mod_productvariants', 'showVariPrice', array($value['preis']))) { ?>
			(<?php echo wpsg_ff($value['preis'], $this->get_option('wpsg_currency')); ?>)
		<?php } ?>
		<br />
		<?php } ?>
		<?php } ?>							
		<?php } else { ?>
		<?php echo $this->view['variante']['key']; ?>
		<?php } ?>
		</strong>
	</div> 
</div>