 <?php

	/**
	 * Render ein Variantenprodukt in der Bestellübersicht (basket.phtml)
	 */

?>
<?php //wpsg_debug($this->view['variante']) ?>
<div class="product_info">
	<div 
	<?php if (wpsg_isTrue($this->view['$bPicture'])) { ?>class="titlep"><?php } else { ?>class="title"><?php } ?>
		<span class="fa  fa-share-alt"></span>
		<?php echo __("Variante", "wpsg"); ?>:
	</div>
	<div class="valuel">
		<?php if (get_option('wpsg_vp_detailview') == 1) { ?>
		<?php foreach ($this->view['variante'] as $vari => $value) { ?>
		
		<?php if (is_numeric($vari)) { ?>
		<?php echo $value['name'] ?>: 
		<strong>
		<?php echo $value['value'] ?>; <?php echo __('Art. Nr.', 'wpsg').': '.$value['artnr'] ?>; 
		<?php if ($this->callMod('wpsg_mod_productvariants', 'showVariPrice', array($value['preis']))) { ?>
			(<?php echo wpsg_ff($value['preis'], $this->get_option('wpsg_currency')); ?>)
		<?php } ?>
		<br />
		<?php } ?>
		<?php } ?>							
		<?php } else { ?>
		<?php echo $this->view['variante']['key']; ?>
		<?php } ?>
		</strong>
	</div>
	<br/>
	
</div>