<?php
	
	/**
	 * User: Daschmi (daschmi@daschmi.de)
	 * Date: 20.07.2019
	 * Time: 15:47
	 */ 
  	
	$arCalculation = &$this->view['basket']['arCalculation'];
	
	if ($this->getFrontendTaxView() === WPSG_BRUTTO) $display_brutto_netto = 'brutto';
	else $display_brutto_netto = 'netto';
	
?>

<?php foreach ($arCalculation['coupon'] as $gs) { ?>
	
	<div class="basket_sum_row">
		<div class="title">
			<a class="wpsg_basket_removelink" href="<?php echo str_replace('&', '&amp;', $this->getRemoveLinkURL('voucher_'.$gs['id'])); ?>" title="<?php echo __('Wertgutschein aus dem Warenkorb entfernen', 'wpsg'); ?>" onclick="return confirm('<?php echo __('Sind Sie sich sicher, dass sie den Wertgutschein aus dem Warenkorb entfernen möchten?', 'wpsg'); ?>');"><img src="<?php echo WPSG_URL; ?>views/gfx/bin_x.png" alt="<?php echo __('Löschen', 'wpsg'); ?>" /></a>
			<?php echo __('Wertgutschein', 'wpsg'); ?> <?php echo ((wpsg_isSizedString($gs['code']))?'('.$gs['code'].')':''); ?>
		</div>
		<?php if (sizeof($this->view['basket']['mwst']) > 1 || $this->get_option('wpsg_showMwstAlways') == '1') { ?>
			<div class="colgsr"><?php echo __('anteilig', 'wpsg'); ?></div>
		<?php } ?>
		<div class="value"><?php
				
				echo wpsg_ff($gs[$display_brutto_netto], $this->get_option('wpsg_currency'));
				
				if (strpos($gs['set'], '%') !== false) {
					
					echo '<span class="procent_payship">('.wpsg_ff(wpsg_tf($gs['set']), '%').')</span>';
					
				}
			
			?></div>
	
	</div>

<?php } ?>

<div class="basket_sum_row">
	<div class="title2">
		<?php echo __('Zu zahlen', 'wpsg'); ?>:
	</div>
	<div class="sum">
		<?php echo wpsg_ff($arCalculation['sum']['topay_brutto'], $this->get_option('wpsg_currency')); ?>
	</div>
</div>
<div class="wpsg_spacer"></div>
