<?php

    /**
     * Template für die Integration der Profilauswahl in die Produktverwaltung (Übersicht)
     */

    $arProfile = $this->callMod('wpsg_mod_export', 'getProfile', array(wpsg_mod_export::TYPE_PRODUCT));

?>

<?php if (wpsg_isSizedArray($arProfile)) { ?>
<div class="wpsg-export container-fluid form-horizontal" style="display:none;">
            
    <form class="container-fluid form-horizontal" target="_blank" method="post" action="<?php echo WPSG_URL_WP ?>wp-admin/admin.php?page=wpsg-Admin&action=module&modul=wpsg_mod_export&do=handleExport&noheader=1" onsubmit="wpsg_mod_export_serializefilter();">

    <div class="row">
		<div class="col-lg-4">

            <?php foreach ($arProfile as $p) { ?>
                <?php echo wpsg_drawForm_Checkbox('wpsg_mod_export_profile[]', $p['name'], false, array('value' => $p['id'], 'noHidden' => true)); ?>
            <?php } ?>

            <br /><?php echo wpsg_drawForm_SubmitButton(__('Export starten')); ?>

        </div>
    </div>

    <input type="hidden" name="filter" id="wpsg_mod_export_filter" value="" />

</form>
        
</div>

<script type="text/javascript">/* <![CDATA[ */
           
    function wpsg_mod_export_serializefilter()
    {

        jQuery('#wpsg_mod_export_filter').val(jQuery('#filter_form').serialize());

    }
    
    jQuery(document).ready(function() {
        
        jQuery('.wpsg_showhide_export').off('click').on('click', function() {
            
            jQuery(this).toggleClass('active');
            jQuery('.wpsg-export').toggle(250);
            
            return false;
            
        } );
        
    } );

/* ]]> */</script>
<?php } ?>