<?php

	/**
	 * Diese Mail wird an den Kunden geschickt, wenn er die Passwort Anfrage erfolgreich bestätigt hat
	 */

    $arPflicht = $this->loadPflichtFeldDaten();
    $arTitle = explode('|', $arPflicht['anrede_auswahl']);

?><?php echo wpsg_translate(__('Hallo #1# #2# #3#,', 'wpsg'), @$arTitle[$this->view['basket']['checkout']['title']], $this->view['basket']['checkout']['vname'], $this->view['basket']['checkout']['name']); ?>
 
 
<?php echo __('Sie haben eine neues Passwort angefragt.', 'wpsg'); ?> 
 
<?php echo wpsg_translate(__('Ihr neues Passwort lautet ab sofort: #1#', 'wpsg'), $this->view['kunde']['passwort']); ?> 
 
<?php echo __('Viele Grüße', 'wpsg'); ?> 
 
<?php echo __($this->get_option('wpsg_shopdata_name'), 'wpsg'); ?> - <?php echo __('Team', 'wpsg'); ?>