<?php

/**
 * Template für die Anzeige der Produktattribute in der Bestellzusammenfassung 
*/
//wpsg_debug($this->view);
?>

<?php foreach ((array)$this->view['wpsg_mod_produktattribute']['data'] as $pa_id) { ?>
<div class="product_info">
	<div 
	<?php if ($this->view['$bPicture'] == true) { ?>class="titlep"><?php } else { ?>class="title"><?php } ?>
		<span class="fa fa-ellipsis-v"></span>
		<?php echo $this->callMod('wpsg_mod_produktattribute', 'getAttributeLabel', array($pa_id)); ?>:
		<strong><?php echo $this->callMod('wpsg_mod_produktattribute', 'getAttributeValue', array($this->view['wpsg_mod_produktattribute']['id'], $pa_id)); ?></strong>
	</div>
</div>
<?php }?>