<?php

	/**
	 * Template für die Integration in order.phtml (Kundenmail, Adminmail, Auftragsbestätigung ...)
	 */	

?><?php echo wpsg_pad_right(' ', 5); ?><?php echo __('Lieferzeit', 'wpsg'); ?>: <?php echo $this->view['wpsg_mod_deliverytime']['deliverytime']; ?> 
<?php		if ($this->view['wpsg_mod_deliverytime']['delaytime'] != '') {
			echo __('<br />', 'wpsg');
			echo __($this->view['wpsg_mod_deliverytime']['delaytime'], 'wpsg');
		}
?>