<?php

	/**
	 * Template für die Konfiguration der Produktvariablen innerhalb der Produktverwaltung
	 */
 
?>
<div class="panel panel-default">
	<div class="panel-heading clearfix">
		<h3 class="panel-title">
			<?php echo __('Produktgruppen', 'wpsg'); ?> 
		</h3>
	</div>
	<div class="panel-body">
		
		<?php if (!wpsg_isSizedArray($this->view['wpsg_mod_productgroups']['data'])) { ?>
		<p><?php echo __('Bisher wurden keine Produktgruppen angelegt.', 'wpsg'); ?></p>
		<?php } else { ?>
		<?php echo wpsg_drawForm_Select('wpsg_productgroup', __('Produktgruppe', 'wpsg'), @$this->view['wpsg_mod_productgroups']['data'], @$this->view['wpsg_mod_productgroups']['produkt_data']['pgruppe']); ?>
		<?php echo wpsg_drawForm_Input('wpsg_productgroup_sticky_von', __('Sticky von', 'wpsg'), @$this->view['wpsg_mod_productgroups']['sticky_von']); ?>
		<?php echo wpsg_drawForm_Input('wpsg_productgroup_sticky_bis', __('Sticky bis', 'wpsg'), @$this->view['wpsg_mod_productgroups']['sticky_bis']); ?>
		<?php } ?>
		 
		<a href="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin&amp;page=wpsg-Productgroups"><span class="wpsg-glyphicon glyphicon glyphicon-book"></span><?php echo __('Produktgruppenverwaltung', 'wpsg'); ?></a><br />
		<a href="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin&action=module&modul=wpsg_mod_productgroups"><span class="wpsg-glyphicon glyphicon glyphicon-wrench"></span><?php echo __('Zur Konfiguration der Produktgruppe', 'wpsg'); ?></a>
		
	</div>
</div>