<script type="text/javascript">
					
	jQuery(document).ready(function() { 
		
		jQuery(".handlediv").bind("click", function() { 
			if (jQuery(this.parentNode).hasClass("closed"))
			{
			
				jQuery.cookie("wpsg_ab_field", "0", { expires: 999999 } );
			
			}
			else
			{
			
				jQuery.cookie("wpsg_ab_field", "1", { expires: 999999 } );
			
			}
		} );

		if (jQuery.cookie("wpsg_ab_field") == "1")
		{
		
			jQuery("#wpsg_ab_postbox").removeClass("closed");
		}
		
	} );

</script>

<?php echo wpsg_drawForm_AdminboxStart(__('Auftragsbestätigung', 'wpsg')); ?>
	
	<div class="inside">						
		<div class="inside" style="padding:5px;">
			
			<p>
				<?php echo __('Die Auftragsbestätigung bestätigt dem Kunden die erfolgreiche Erfassung des Auftrages. Abweichungen vom Auftrag können mittels des Textfeldes mitgesendet werden.', 'wpsg'); ?>
				<?php echo __('Der Status ändert sich automatisch auf "Bestätigt".', 'wpsg'); ?>
			</p>
			
			<br />
			
			<form method="post" action="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Order&action=ajax&mod=wpsg_mod_auftragsbestaetigung&edit_id=<?php echo $this->view['data']['id']; ?>&noheader=1">			
				<div style="padding-left:5px;">
					<textarea style="width:100%;" class="wpsg_order_view_auftragsbestaetigung" name="auftrag_note"></textarea>
				</div>
				<input class="button" style="float:right; margin-right:10px;" type="submit" value="<?php echo __('Senden', 'wpsg'); ?>" /><br />
				<input type="hidden" name="mod_auftragbestaetigung" value="1"/>
			</form>
			
		</div>
	</div>
	
<?php echo wpsg_drawForm_AdminboxEnd(); ?>