<?php

	/**
	 * Template für die Anzeige des Gesamtgewichts innerhalb des Warenkorbs
	 */

?>
<div class="basket_sum_row">
	<div class="title">
		<?php echo __('Gesamtgewicht', 'wpsg'); ?>:
	</div>
	<div class="value">
		<?php echo wpsg_ff($this->view['wpsg_mod_weight']['weight'], $this->get_option('wpsg_mod_weight_unit')); ?>
	</div>
    <div class="value">
        <?php echo __('&nbsp;'); ?>
    </div>
</div>